day1:
  title: "Day 1: Introduction to Galaxy and NGS analysis"
  sessions:
    - name: Welcome & Course Information (Click here to start)
      description: "Start here; we will go over all the important things to know to get the most out of this workshop"
      speaker: shiltemann
      type: lecture
      video: g_cavAO-fBM
      video_time: 30M
      support_channel: "#general"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01ES8R0RNG"

    - name: "Say Hi in Slack!"
      type: icebreaker
      prompt: "Introduce yourself and let us know where you are joining from today"
      example: "Hi! My name is Saskia and I am joining from The Netherlands, I am currently in my hammock looking at the snow falling down outside."

    - name: "Using Galaxy: An introduction to NGS analysis"
      description: "This tutorial will introduce the Galaxy platform and walk you through an NGS analysis step by step."
      video: g_cavAO-fBM
      speaker: nekrut
      video_length: 1H30M
      material:
        - type: slides
          link: /topics/introduction/slides/introduction.html
          title: Introduction to Galaxy
        - type: tutorial
          link: /topics/introduction/tutorials/galaxy-intro-101/tutorial.html
          title: Galaxy 101
        - type: tutorial
          link: /variant-analysis/tutorials/sars-cov-2/tutorial.html
          title: SARS-CoV-2 variant analysis
      support_channel: "#1-1_galaxy-intro"
      support_link: https://gtnsmrgsbord.slack.com/archives/C01ES914GCU



    - name: "Introduction to Quality Control"
      speaker: heylf
      type: Lecture
      video: BWonTPS4zB8
      time: 40M
      material:
        - type: slides
          link: /topics/sequence-analysis/tutorials/quality-control/slides.html
          title: Introduction to Quality Control
      support_channel: "#1-3_quality-control"
      support_link: https://gtnsmrgsbord.slack.com/archives/C01FQ92MB7A


    - name: "Quality Control"
      type: Hands-on
      video: QJRlX2hWDKM
      speaker: heylf
      time: 1H10M
      material:
        - type: tutorial
          link: "topics/sequence-analysis/tutorials/quality-control/tutorial.html"
      support_channel: "#1-3_quality-control"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01FQ92MB7A"


    - name: "Introduction to Mapping"
      type: Lecture
      speaker: pvanheus
      time: 10M
      video: 7FhHb8EV3EU
      material:
        - type: slides
          link: topics/sequence-analysis/tutorials/mapping/slides.html
          title: Mapping
      support_channel: "#1-4_mapping"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01F6JHCFT6"


    - name: "Mapping"
      type: Hands-on
      speaker: pvanheus
      video: 1wm-62E2NkY
      video_length: 20M
      material:
        - type: tutorial
          link: topics/sequence-analysis/tutorials/mapping/tutorial.html
          title: Mapping
      support_channel: "#1-4_mapping"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01F6JHCFT6"


    - name: "Introduction to Genome Assembly"
      type: Lecture
      speaker: slugger70
      video: "eyfCyINTD_E" # TODO: update
      video_length: ""
      material:
       - type: slides
         link: topics/assembly/tutorials/general-introduction/slides.html
         title: An Introduction to Genome Assembly
      support_channel: "#1-5_assembly"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01EKMD8VC7"



    - name: "Genome Assembly"
      type: Hands-on
      speaker: annasyme
      video: eyfCyINTD_E
      video_length: 35M
      material:
       - type: tutorial
         link: topics/assembly/tutorials/chloroplast-assembly/tutorial.html
         title: Chloroplast genome assembly
      support_channel: "#1-5_assembly"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01EKMD8VC7"



day2:
  title: "Day 2: Introduction to RNA-Seq analysis with Galaxy and R"
  sessions:
    - name: "Introduction to RNA-Seq"
      speaker: fpsom
      video: qKkS_tztw_Q
      video_lenth: 30M
      material:
        - type: slides
          link: topics/transcriptomics/slides/introduction.html
          title: Introduction to Transcriptomics
      support_channel: "#2-1_ref-based-rna-seq"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01F0L6UW03"

    - name: Reference-based RNA-seq Analysis
      speaker: bebatut
      video: 37Tc1xnrHK4
      video_length: 2H30M
      material:
        - type: tutorial
          link: topics/transcriptomics/tutorials/ref-based/tutorial.html
          title: Reference-based RNA-Seq data analysis
      support_channel: "#2-1_ref-based-rna-seq"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01F0L6UW03"
